# Component documentation and configuration
status: 'production'
classBase: 'c-media'
displayName: 'Media'
flavours:
  - base
dependencies:
  - core

# Generates the `Data` table
schema:
  title:
    type: string
    description: ""

# Generates the `Usage` table
usage:
  - class: .c-media
    required: True
    elements:
      - div
    outcome: Defines the Media component
    comments: Wrapping element, adds margin at bottom
